import numpy as np


InstrumentFamily_map = {

   'String': ['bass 1', 'bass 2', 'a.guitar', 'e.guitar', 'strings', 'acou bass', 'clean gtr', 'jazz gtr', 'bas', 'fretless bass', 'violin', 'accordation', 
              'fingered bass', 'clean guitar', 'muted guitar', 'steel guitar', 'ac. bass', 'fiddle', 'jazz guitar', 'strings2', 'syn strings', 'harp', 
              'bass', 'guitar 2', 'guitar', 'nylon guitar', 'chords', 'basso', 'slowstrin', 'steel gt', 'archi', 'nylon gt',  'guitar', 'guitar 2', 
              'guitar 3', 'el guitar', 'muted gtr', 'muted gt', 'guitar 1', 'guitar solo', 'guitar 4', 'guitar 5', 'acoustic guitar', 'lead guitar', 
              'bass guitar', 'nylon gtr', 'steel gtr', '12str gtr', 'chorus gt', 'funk gtr', 'fretless', 'slapbass 1', 'fingerdbas', 'fing.bass', 
              'bass&lead', 'syn bass 2', 'bass', 'baixo', 'guitare', 'electric bass (finger)', 'pick bass', 'jazz bass', 'bass line', 'slap bass 2', 
               'bass gtr', 'ac bass', 'fingerdba', 'fretless', 'viola', 'cello', 'pizzicato', 'ac guitar', 'ac. guitar', 'rhythm guitar', 
               'distorted guitar', 'overdriven guitar', 'distortion guitar', 'overdrive guitar', 'guitar i', 'guitar ii', 'guitar1', 
               'guitar2', 'elec guitar', 'banjo', 'charang', 'nylon gtr', '12str gtr', 'chorus gt', 'funk gtr', 'synth bass', 'syn bass 1', 'syn bass 2', 
               '+synbass 3', 'pizzicato', 'string1', 'gtharmonic', 'string 2', 'basse', 'acoustic bass', 'contrabass', 'bass guitar', 'el bass', 
               'fingered', 'fingerbas', 'slap bass', 'slapbass 1', 'slapbass 2', 'bass', 'bass    (bb)', 'acoubass', 'jazz electric', 'electric guitar', 
               'elec guit', 'elec. guitar', 'electric', 'clean gt', 'clean gt.', 'distorted', 'distortio', 'guitar3', 'guitarra', 'steel string', 
               'solo guitar', 'rhythm gu', 'muted gt.', 'acoustic', 'acoustic ', 'nylon gtr', 'banjo', 'viola', 'cello', 'low strings', 'string ensemble',
               'string', 'strings', 'strings 1', 'strings', 'string 1', 'slow strings', 'slow str', 'synth strings', 'pizzicato','electric bass', 
               'fretless bass', 'fretless e bass', 'fretless e.bass', 'fretless e. bass','bass', 'base', 'bass    (bb)', 'picked bass', 'slap bass', 
               'fingered bass', 'acoustic guitar (steel)','electric guitar', 'e. guitar', 'electric guitar (clean)', 'clean guitar', 'clean gt.', 
               'clean guit','distortion guitar', 'dist', 'muted guitar', 'mute guitar', 'muted guitar', 'guitar  (bb)','guitar 1', 'guitar 3', 
               'gitarre', 'lead gtr', 'lead gtr muted', 'guitar i', 'electric guitar i','electric guitar ii', 'electric guitar iii', 'shamisen', 
               'koto', 'cello', 'viola', 'harp','harpsichord', 'harpsichrd'],

   'Keyboard': ['e.piano', 'a.piano', 'celesta', 'organ 1', 'piano', 'lead', 'honky tonk', 'bright piano', 'grand piano', 'hammond', 'a.piano 2', 
                'a.piano 3', 'e.piano 2', 'piano1', 'organ', 'organ 3', 'synthbrass', 'syn str 1', 'calliope', 'marimba', 'crystal', 'melodia', 
                'a.piano', 'ac piano', 'piano', 'piano1', 'piano 1', 'piano 2', 'piano2', 'rhodes', 'clavinet', 'organ', 'organ 2', 'church org', 
                'elec organ', 'keyboard', 'marimba', 'vibraphone', 'glockenspl', 'kalimba', 'warm pad', 'polysynth', 'synth pad', 'synth 1', 'synth 2', 
                'chiffer ld', 'electric piano', 'elec piano', 'elec pian', 'rock organ', 'reed organ', 'organ', 'harpsichrd', 'clavinet', 'rhodes', 
                'warmpad', 'warm pad', 'pad', 'sweep pad', 'polysynth', 'keyboard', 'keyboard 1', 'keyboard 2', 'marimba', 'glockenspl', 'celesta', 
                'tinklebell', 'vibraphone','hammond organ', 'piano', 'piano    (bb)', 'grand piano *merged', 'bright acoustic piano','adlib piano', 
                'piano 2', 'e piano', 'el piano', 'el.piano', 'rhodes piano', 'rhodes','electric piano', 'clavinet', 'music box', 'celesta', 'xylophone', 
                'vibes', 'marimba'],

   'Aerophone': ['clarinet', 'flute', 'tuba', 'trumpet', 'trombone', 'fr.horn', 'brass 1', 'brass', 'ocarina',  'pan flute', 'oboe', 'alto sax', 
                 'tenor sax', 'baritonsax', 'harmonica', 'sitar', 'voice oohs', 'choir aahs', 'alto sax', 'bari sax', 'baritonsax', 'trumpet 1', 
                 'trumpet 2', 'trumpet 3', 'trumpet 4', 'trombone', 'french horn', 'horn', 'brass section', 'piccolo', 'flute', 'shakuhachi', 'bassoon', 
                 'oboe', 'pan flute', 'sax', 'tubularbel','sopran sax', 'baritone sax', 'alto sax', 'piccolo', 'recorder', 'flute', 'shakuhachi', 
                 'oboe', 'bassoon', 'french horn', 'trumpet', 'trombone', 'brass section', 'pan flute', 'harmony', 'choir aah', 'choir aahs', 'voice ooh',
                   'chant', 'vox', 'syn vox','brass', 'brass 2', 'synth brass', 'synbrass', 'synth brass 2', 'trombone', 'trompete','horns', 'sax', 
                   'flute', 'piccolo', 'recorder', 'oboe', 'bassoon', 'harmonica', 'pan flute','shakuhachi', 'koto', 'shamisen'],

   'Percussion': ['drums', 'hi-hats', 'tambourine', 'shaker', 'bass drum', 'taiko', 'percussion', 'toms', 'low tom', 'kick', 'snare', 'drum', 'batteria', 
                  'hihat', 'snare', 'kick', 'snare drum', 'closed h.h', 'ride cymb', 'handclap', 'cymbal', 'tambourin', 'toms', 'claps', 'shaker', 
                  'bassdrum', 'synth drum', 'drums', 'batera', 'melo tom 1', 'drums', 'drum', 'drummix', 'jazz kit', 'kick drum', 'kick drum 1', 
                  'snare', 'hihat', 'hihats', 'hi hat', 'closed hi-hat', 'cymbals', 'ride cymbal', 'tamborine', 'cabasa', 'timpani', 'claps', 'shaker', 
                  'perc', 'orch.hit', 'bell', 'handclap','drumz', 'drums', 'drums   (bb)', 'drum mix', 'kick', 'kick drum', 'bass drum', 'bass drum', 
                  'snare dru', 'sn', 'snare', 'hihats', 'hi-hat', 'open hi hat', 'open hihat', 'closed h.', 'hh', 'crash', 'crash cymb', 'ride', 
                  'ride cymbal', 'toms', 'high tom', 'mid tom', 'sidestick', 'woodblock', 'bongos', 'low conga', 'high conga', 'cowbell', 'steeldrums', 
                  'steel drums', 'agogo', 'cabasa', 'tamborine', 'reverscymb', 'ice rain', 'bowedglass', 'timpani', 'tubularbel', 'orch.hit', 
                  'drums', 'drums   (bb)', 'drums2', 'drums 2', 'drums 1', 'drum set', 'std drums', 'std drum set','gm drums', 'bassdrum', 'bass dru', 
                  'kick 1 36', 'snare', 'snare drum', 'snare    ', 'hihat','hi-hat', 'closed hi hat', 'closed hihat', 'closed hh', 'closed hi', 
                  'hh clsd  42', 'ride','ride', 'cymbals', 'rim shot', 'congas', 'maracas', 'steel drum', 'steel drum','orchestra hit', 
                  'orch.hit', 'bells', 'toms', 'tom mid 2', 'mid tom', 'high tom', 'majortom','woodblock', 'cabasa', 'tambourine', 'bongos', 'cowbell'],

   'Voice': ['choir', 'melody', 'melody 2', 'words', 'voice', 'cori', 'canto', 'rhythm', 'whistle', 'vocals', 'voz', 'vocal-lin', 'synvox', 'vocal', 
             'voice oohs', 'vocals', 'vocals 1', 'vocals 2', 'lead vocal', 'background vocals', 'choir', 'choir ah', 'choir aahs', 'voice oohs', 
             'voices', 'lyrics', 'vocal', 'vocal 1', 'vocal 2', 'synvox', 'vocoder','lead vocals', 'backing vocals', 'backup vocals', 'backup', 
             'vocals', 'vocal', 'vox', 'voices', 'choir', 'syn vox', 'chant', 'harmony', 'lyrics','lead vox', 'solo vox', 'vocal', 'voice 1 (melody)', 
             'voice 2 (harmony)', 'synth voice','spacevoice', 'choir', 'chant', 'background vocals', 'lead', 'lead 2 (sawtooth)', 'vox','backing vocals', 
             'harmony', 'choir aahs', 'voice ooh'],

   'Sync': ['synth', 'fantasia', 'saw wave', 'squarewave', 'overdrive', 'slowstring', 'brightness', 'synthbrass', 'syn str 1', 'calliope', 'crystal', 
            'synvox', 'synth bass', 'syn bass', 'synth bass 2', 'synbrass 1', 'synbrass 2', 'syn string', 'syn str 2', 'saw', 'sawtooth', 'squarewave', 
            'atmosphere', 'crystal', 'chiffer ld', 'distortion', 'synth pad', 'polysynth', 'warm pad', 'slowstring', 'brightness', 'calliope', 
            'synth bass', 'synthbass', 'synth bas', 'synth bass 1', 'synthbrass 1', 'synth strings', 'synth pad', 'warm pad', 'atmosphere', 'crystal', 
            'polysynth', 'sweep pad', 'squarewave', 'sawtooth', 'distortion', 'pad', 'synvox', 'brightness', 'slow pad', 'calliope','synth brass', 
            'synbrass', 'synth brass 2', 'synthstrings 1', 'synth voice', 'spacevoice','metal pad', 'pad 7 (halo)', 'pad 3 (polysynth)', 
            'pad 1 (new age)', 'warm pad', 'sweep pad','polysynth', 'sinth', 'lead 2 (sawtooth)', 'echo drops', 'ice rain', 'brightness', 
            'crystal','atmosphere', 'fantasy', 'bandneon'],

   'Others': ['', 'halo pad', 'staff-1', 'staff-2', 'staff-3', 'staff-4', 'staff-5', 'staff-6', 'staff-7', 'track 2', 'track 3', 'track 4', 'track 5', 
              'track 6', 'track 10', 'track 1', 'track 11', 'tk1', 'tk2', 'tk3', 'tk4', 'tk5', 'tk6', 'tk7', 'tk8', 'tk10', 'unnamed-000', 'unnamed-001', 
              'tk9', 'tk11', 'tk12', 'tk13', 'tk14', 'tk15', 'track 7', 'staff', 'staff-8', 'staff-9', 'unnamed-003']
    
}
